baseURL = "/"
languageCode = "en-us"
title = "YouTube Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "YouTube"
    subsite = "youtube"
    description = "YouTube is not what it seems."
    tagline = "youtube is one of the way information spread; Together, we can study its power.."

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Youtuber Labor union"
    identifier = "SeeYou"
    name = "the Youtuber Labor union"
    url = "/seeyou/"
    weight = -180

 [[menu.main]]
    page = "More"
    identifier = "more"
    name = "More"
    url = "#"
    weight = -100
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "more"
    weight = -110
 [[menu.main]]
    page = "API Documentation"
    identifier = "api-documentation"
    parent = "more"
    name = "API Documentation"
    url = "/api-documentation/"
    weight = -130
 [[menu.main]]
    page = "Get Involved"
    identifier = "get-involved"
    name = "Get Involved"
    parent = "more"
    url = "/get-involved/"
    weight = -140
 [[menu.main]]
    page = "What We Collect, how does it work"
    identifier = "what-we-collect"
    name = "What We Collect"
    parent = "more"
    url = "/what-we-collect/"
    weight = -150
 [[menu.main]]
    page = "first results"
    identifier = "first-results"
    name = "First results"
    parent = "more"
    url = "/results/"
    weight = -160

 [[menu.featured]]
    page = "compare"
    identifier = "compare"
    name = "Compare"
    url = "/yttrex/compare/"
    weight = -180
    pre = "/images/yt-compare.jpg"
    post = "Compare how a video gets different reccomendations"
 [[menu.featured]]
    page = "related"
    identifier = "related"
    name= "Related"
    url = "/yttrex/related/"
    pre = "/images/yt-search.jpg"
    post = "Search if a video has ever been recommended by YouTube"
    weight = -170
 [[menu.featured]]
    page = "last"
    identifier = "last"
    name = "Last"
    url = "/yttrex/last/"
    pre = "/images/yt-last.jpg"
    post = "The lastest videos we have collected with our monitoring tools"
    weight = -160

 [[menu.footer]]
    page = "Project analysis"
    identifier = "background"
    name = "Project analysis"
    url = "/background/"
    weight = 100

